# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
steps:
  # Install dependencies
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']

  # Test
  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'test']

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/project1-cart-service:${SHORT_SHA}',
        '.',
      ]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/project1-cart-service:${SHORT_SHA}',
      ]

# Save test logs to Google Cloud Storage
artifacts:
  objects:
    location: gs://${_BUCKET_NAME}/
    paths:
      - ${SHORT_SHA}_test_log.xml

# Store images in Google Artifact Registry
images:
  - us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/project1-cart-service:${SHORT_SHA}

# options
options:
  logging: CLOUD_LOGGING_ONLY
